# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1fkyj4fyTDvDFNzm066g9Js85s6xoPMNv
"""

list1 = [12, -7, 5, 64, -14]
list2 = [12, 14, -95, 3]

print("l1:", positive_numbers_list1)
print( "l2:", positive_numbers_list2)