# -*- coding: utf-8 -*-
"""AI ASSIGNMENT-Set Operations.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1AiDZpA73hd5gN15fK1MLXBOtaB7SAUJ0
"""

E = {0, 2, 4, 6, 8}
N = {1, 2, 3, 4, 5}

print("Union of E and N is:", E | N)
print("Intersection of E and N is:", E & N)
print("Difference of E and N is:", E - N)
print("Symmetric difference of E and N is:", E ^ N)